import { FiCreditCard, FiHeart, FiStar, FiTruck } from "react-icons/fi";

export const upperHeaderData = [
    "Free Shipping above RS 4500",
    "Hassle-Free Returns",
    "15000+ Orders, 1000+ 5⭐ Reviews"
]


export const trustData = [
  {
    icon: FiHeart,
    heading: "150,000+ Orders Delivered",
    desc: "Trusted by modest wear lovers worldwide.",
  },
  {
    icon: FiTruck,
    heading: "Fast Nationwide Delivery",
    desc: "Swift Delivery. Seamless Support. Tailored for You.",
  },
  {
    icon: FiCreditCard,
    heading: "COD Available",
    desc: "Secure your order now and pay when it arrives.",
  },
  {
    icon: FiStar,
    heading: "Premium Quality",
    desc: "From fit to fabric, your voice shapes everything we create.",
  },
];

export const byCollection = [
    {image: "/collectiondemo.jpg", link: "/collections/hijab-georgette" , title: "Georgette"},
    {image: "/collectiondemo.jpg", link: "/collections/hijab-lawn" , title: "Lawn"},
    {image: "/collectiondemo.jpg", link: "/collections/hijab-silk" , title: "Silk"},
]

// export const essentials = [
//     {image: "/essentials.jpg", link: "#", title: "Magnets and Pins"},
//     {image: "/essentials.jpg", link: "#", title: "Underscarves"},
//     {image: "/essentials.jpg", link: "#", title: "Scrunchies"},
//     {image: "/essentials.jpg", link: "#", title: "Niqab"},
// ]

export const reviews = [
  {
    id: 1,
    name: "Aisha Khan",
    role: "Customer",
    review: "Absolutely love the quality! Delivery was fast and the product exceeded my expectations.",
  },
  {
    id: 2,
    name: "Omar Malik",
    role: "Verified Buyer",
    review: "Great experience. The website is easy to use and support was very responsive.",
  },
  {
    id: 3,
    name: "Sana Ali",
    role: "Customer",
    review: "Beautiful packaging and excellent fabric. Will definitely order again.",
  },
  {
    id: 4,
    name: "Ahmed Raza",
    role: "Customer",
    review: "Customer service was amazing. They helped me choose the right size perfectly.",
  },
  {
    id: 5,
    name: "Fatima Noor",
    role: "Verified Buyer",
    review: "The quality feels premium and fits really well. Highly recommended!",
  },
  {
    id: 6,
    name: "Bilal Hussain",
    role: "Customer",
    review: "Loved it! True to description and delivery was right on time.",
  },
  {
    id: 7,
    name: "Zara Imtiaz",
    role: "Customer",
    review: "Simple, elegant and exactly what I wanted. Great job!",
  },
  {
    id: 8,
    name: "Hassan Qureshi",
    role: "Verified Buyer",
    review: "Good experience overall. Great prices and fast delivery.",
  },
  {
    id: 9,
    name: "Maryam Javed",
    role: "Customer",
    review: "Amazing service, quality and support. I’ll definitely recommend to friends.",
  },
];

export const sidebarData = [
  { title: "Home", link: "/", delay: 0.1 },

  {
    title: "Dupatta",
    delay: 0.2,
    children: [
      { title: "Chiffon Dupatta", link: "/collections/dupatta-chiffon" },
      { title: "Lawn Cutwork Dupatta", link: "/collections/dupatta-lawn-cutwork" },
      { title: "Jackard Dupatta", link: "/collections/dupatta-jackard" },
      { title: "Organza Dupatta", link: "/collections/dupatta-organza" },
      { title: "Silk Dupatta", link: "/collections/dupatta-silk" },
      { title: "Four Sided Border Dupatta", link: "/collections/dupatta-four-sided-border" },
      { title: "Fancy Dupatta", link: "/collections/dupatta-fancy" },
    ],
  },

  {
    title: "Hijab",
    delay: 0.3,
    children: [
      { title: "Silk Hijab", link: "/collections/hijab-silk" },
      { title: "Lawn Hijab", link: "/collections/hijab-lawn" },
      { title: "Georgette Hijab", link: "/collections/hijab-georgette" },
    ],
  },

  { title: "Chaddar", link: "/collections/chaddar", delay: 0.4 },

  { title: "Blog", link: "/blog", delay: 0.5 },
];


export const collectionsPage = [
  // Dupatta Collections
  { title: "Chiffon Dupatta", link: "/collections/dupatta-chiffon", image: "/collectiondemo.jpg", delay: 0.1 },
  { title: "Lawn Cutwork Dupatta", link: "/collections/dupatta-lawn-cutwork", image: "/collectiondemo.jpg", delay: 0.2 },
  { title: "Jackard Dupatta", link: "/collections/dupatta-jackard", image: "/collectiondemo.jpg", delay: 0.3 },
  { title: "Organza Dupatta", link: "/collections/dupatta-organza", image: "/collectiondemo.jpg", delay: 0.4 },
  { title: "Silk Dupatta", link: "/collections/dupatta-silk", image: "/collectiondemo.jpg", delay: 0.5 },
  { title: "Four Sided Border Dupatta", link: "/collections/dupatta-four-sided-border", image: "/collectiondemo.jpg", delay: 0.6 },
  { title: "Fancy Dupatta", link: "/collections/dupatta-fancy", image: "/collectiondemo.jpg", delay: 0.7 },

  // Hijab Collections
  { title: "Silk Hijab", link: "/collections/hijab-silk", image: "/collectiondemo.jpg", delay: 0.8 },
  { title: "Lawn Hijab", link: "/collections/hijab-lawn", image: "/collectiondemo.jpg", delay: 0.9 },
  { title: "Georgette Hijab", link: "/collections/hijab-georgette", image: "/collectiondemo.jpg", delay: 1.0 },

  // Chaddar Collection
  { title: "Chaddar", link: "/collections/chaddar", image: "/collectiondemo.jpg", delay: 1.1 },
];


export const collectionsData = [
  {
    title: "Chiffon Dupatta",
    slug: "dupatta-chiffon",
    desc: "Lightweight, elegant, and perfect for both casual and festive wear — our chiffon dupattas add effortless grace to any outfit.",
    products: [
      {
        id: 1,
        name: "Sheer Elegance Chiffon Dupatta",
        desc: "A sheer chiffon dupatta with soft texture and delicate fall, ideal for evening wear.",
        price: 2199,
        newPrice: 1799,
        onSale: true,
        images: ["/collectiondemo.jpg", "/essentials.jpg"],
        colors: ["Red", "Peach", "Sky Blue", "Off White", "Black"],
      },
      {
        id: 2,
        name: "Classic Plain Chiffon Dupatta",
        desc: "Minimalist plain chiffon dupatta offering timeless versatility for any dress.",
        price: 1999,
        newPrice: 1699,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["White", "Maroon", "Beige", "Grey", "Baby Pink"],
      },
      {
        id: 3,
        name: "Luxury Embroidered Chiffon Dupatta",
        desc: "Soft chiffon dupatta with delicate embroidery for a luxurious festive look.",
        price: 2399,
        newPrice: 1999,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Champagne", "Lavender", "Mint", "Ivory", "Rose"],
      },
    ],
  },
  {
    title: "Lawn Cutwork Dupatta",
    slug: "dupatta-lawn-cutwork",
    desc: "Soft lawn dupattas with delicate cutwork details, designed for comfort and breathable elegance.",
    products: [
      {
        id: 4,
        name: "Pastel Cutwork Lawn Dupatta",
        desc: "Pastel-toned lawn dupatta with fine cutwork edges for a light and airy look.",
        price: 1899,
        newPrice: 1599,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Mint", "Peach", "Sky Blue", "Lemon", "White"],
      },
      {
        id: 5,
        name: "Embroidered Edge Lawn Dupatta",
        desc: "Soft lawn fabric with embroidered edges, perfect for daily wear or semi-formal events.",
        price: 1799,
        newPrice: 1499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Olive", "Dusty Pink", "Off White", "Sea Green", "Lavender"],
      },
      {
        id: 6,
        name: "Soft Breeze Lawn Dupatta",
        desc: "Lightweight lawn dupatta with breathable texture and subtle print.",
        price: 1699,
        newPrice: 1399,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Blue", "Grey", "Pink", "White", "Mustard"],
      },
    ],
  },
  {
    title: "Jackard Dupatta",
    slug: "dupatta-jackard",
    desc: "Richly woven jacquard dupattas with subtle patterns — a timeless symbol of luxury and tradition.",
    products: [
      {
        id: 7,
        name: "Classic Jackard Dupatta",
        desc: "Traditional jacquard weave in elegant tones for a heritage-inspired look.",
        price: 2199,
        newPrice: 1899,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Gold", "Maroon", "Navy", "Olive", "Black"],
      },
      {
        id: 8,
        name: "Golden Weave Jackard Dupatta",
        desc: "Gold-thread jacquard dupatta that adds festive charm and refinement.",
        price: 2299,
        newPrice: 1999,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Champagne", "Silver", "Ivory", "Emerald", "Wine"],
      },
      {
        id: 9,
        name: "Textured Jackard Dupatta",
        desc: "Subtle texture and intricate weave make this jacquard dupatta a timeless choice.",
        price: 2099,
        newPrice: 1799,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Beige", "Rust", "Navy", "Black", "White"],
      },
    ],
  },
  {
    title: "Organza Dupatta",
    slug: "dupatta-organza",
    desc: "Sheer, glossy organza dupattas that bring a touch of glamour to festive and formal looks.",
    products: [
      {
        id: 10,
        name: "Elegant Sheer Organza Dupatta",
        desc: "Transparent organza dupatta that enhances your traditional outfit with shine.",
        price: 2499,
        newPrice: 2099,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["White", "Blush", "Mint", "Sky Blue", "Lilac"],
      },
      {
        id: 11,
        name: "Crystal Touch Organza Dupatta",
        desc: "Glossy organza with crystal-like shimmer for a refined, festive appearance.",
        price: 2599,
        newPrice: 2299,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Champagne", "Gold", "Peach", "Pink", "Silver"],
      },
      {
        id: 12,
        name: "Luxe Embroidered Organza Dupatta",
        desc: "Hand-embroidered organza dupatta perfect for weddings and celebrations.",
        price: 2799,
        newPrice: 2499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Maroon", "Teal", "Emerald", "Ivory", "Black"],
      },
    ],
  },
  {
    title: "Silk Dupatta",
    slug: "dupatta-silk",
    desc: "Smooth and lustrous silk dupattas — perfect for festive, wedding, or statement occasions.",
    products: [
      {
        id: 13,
        name: "Pure Soft Silk Dupatta",
        desc: "Ultra-soft silk dupatta with subtle shine and graceful drape.",
        price: 2299,
        newPrice: 1999,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Red", "Maroon", "Black", "Champagne", "Navy"],
      },
      {
        id: 14,
        name: "Luxury Printed Silk Dupatta",
        desc: "Printed silk dupatta with rich colors for a luxurious ethnic look.",
        price: 2499,
        newPrice: 2199,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Gold", "Blue", "White", "Pink", "Green"],
      },
      {
        id: 15,
        name: "Everyday Smooth Silk Dupatta",
        desc: "Lightweight silk dupatta ideal for both everyday and formal use.",
        price: 2099,
        newPrice: 1799,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Peach", "Beige", "Grey", "Black", "Off White"],
      },
    ],
  },
  {
    title: "Four Sided Border Dupatta",
    slug: "dupatta-four-sided-border",
    desc: "Beautifully bordered dupattas with detailed lace or embroidery along all four sides.",
    products: [
      {
        id: 16,
        name: "Classic Border Dupatta",
        desc: "Traditional four-sided border design with fine detailing.",
        price: 1899,
        newPrice: 1599,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["White", "Beige", "Sky Blue", "Mint", "Peach"],
      },
      {
        id: 17,
        name: "Elegant Four-Side Border Dupatta",
        desc: "Chic lace-bordered dupatta adding charm to any ensemble.",
        price: 2099,
        newPrice: 1799,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Lavender", "Pink", "Off White", "Maroon", "Teal"],
      },
      {
        id: 18,
        name: "Premium Lace Border Dupatta",
        desc: "Luxurious dupatta with handcrafted lace borders on all sides.",
        price: 2199,
        newPrice: 1899,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Grey", "Ivory", "Blue", "Gold", "Beige"],
      },
    ],
  },
  {
    title: "Fancy Dupatta",
    slug: "dupatta-fancy",
    desc: "Shimmery and festive dupattas crafted for parties, events, and celebrations.",
    products: [
      {
        id: 19,
        name: "Festive Fancy Dupatta",
        desc: "Sparkling dupatta with sequin work ideal for celebrations.",
        price: 2799,
        newPrice: 2499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Gold", "Silver", "Champagne", "Rose Gold", "Black"],
      },
      {
        id: 20,
        name: "Shimmery Net Fancy Dupatta",
        desc: "Net dupatta with glitter highlights perfect for party looks.",
        price: 2599,
        newPrice: 2299,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Pink", "Peach", "White", "Lilac", "Blue"],
      },
      {
        id: 21,
        name: "Party Wear Fancy Dupatta",
        desc: "Stylish dupatta with ornate embroidery and sparkle detailing.",
        price: 2899,
        newPrice: 2599,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Red", "Maroon", "Silver", "Champagne", "Green"],
      },
    ],
  },
  {
    title: "Silk Hijab",
    slug: "hijab-silk",
    desc: "Luxurious silk hijabs offering shine, softness, and sophistication for every occasion.",
    products: [
      {
        id: 22,
        name: "Pure Soft Silk Hijab",
        desc: "Soft silk hijab with smooth finish and elegant sheen.",
        price: 2299,
        newPrice: 1999,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Black", "White", "Maroon", "Beige", "Navy"],
      },
      {
        id: 23,
        name: "Luxury Printed Silk Hijab",
        desc: "Premium silk hijab with modern prints for a chic style.",
        price: 2499,
        newPrice: 2199,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Olive", "Grey", "Gold", "Pink", "Teal"],
      },
      {
        id: 24,
        name: "Everyday Smooth Silk Hijab",
        desc: "Light and breathable silk hijab designed for everyday use.",
        price: 2099,
        newPrice: 1799,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Off White", "Peach", "Lavender", "Dusty Pink", "Blue"],
      },
    ],
  },
  {
    title: "Lawn Hijab",
    slug: "hijab-lawn",
    desc: "Soft, breathable lawn hijabs that are ideal for everyday wear in all seasons.",
    products: [
      {
        id: 25,
        name: "Floral Breeze Lawn Hijab",
        desc: "Printed lawn hijab with floral patterns and light texture.",
        price: 1799,
        newPrice: 1499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Pink", "White", "Sky Blue", "Yellow", "Green"],
      },
      {
        id: 26,
        name: "Summer Lawn Hijab",
        desc: "Ultra-soft lawn hijab for a cool and comfortable summer experience.",
        price: 1699,
        newPrice: 1399,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Mint", "Lavender", "Peach", "Off White", "Grey"],
      },
      {
        id: 27,
        name: "Cutwork Design Lawn Hijab",
        desc: "Elegant lawn hijab featuring delicate cutwork embroidery.",
        price: 1899,
        newPrice: 1599,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Beige", "Blue", "Pink", "Green", "White"],
      },
    ],
  },
  {
    title: "Georgette Hijab",
    slug: "hijab-georgette",
    desc: "Lightweight and easy to style, georgette hijabs offer a graceful drape and elegant texture.",
    products: [
      {
        id: 28,
        name: "Lightweight Georgette Hijab",
        desc: "Soft georgette hijab that drapes beautifully for daily wear.",
        price: 1899,
        newPrice: 1599,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Beige", "Maroon", "Black", "White", "Grey"],
      },
      {
        id: 29,
        name: "Textured Plain Georgette Hijab",
        desc: "Plain georgette hijab with matte texture and rich fall.",
        price: 1799,
        newPrice: 1499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Blue", "Peach", "Olive", "White", "Pink"],
      },
      {
        id: 30,
        name: "Elegant Fall Georgette Hijab",
        desc: "Light, elegant georgette hijab with perfect flow and comfort.",
        price: 1999,
        newPrice: 1699,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Dusty Pink", "Ivory", "Navy", "Grey", "Black"],
      },
    ],
  },
  {
    title: "Chaddar",
    slug: "chaddar",
    desc: "Warm, soft, and elegant chaddars crafted for comfort and modest sophistication.",
    products: [
      {
        id: 31,
        name: "Warm Woolen Chaddar",
        desc: "Cozy woolen chaddar offering warmth and a classic traditional touch.",
        price: 2799,
        newPrice: 2499,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Grey", "Maroon", "Brown", "Beige", "Black"],
      },
      {
        id: 32,
        name: "Classic Handwoven Chaddar",
        desc: "Handwoven chaddar made with care and authentic craftsmanship.",
        price: 2999,
        newPrice: 2699,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Cream", "Grey", "Rust", "Olive", "White"],
      },
      {
        id: 33,
        name: "Soft Cashmere Chaddar",
        desc: "Luxurious cashmere chaddar that combines softness with timeless elegance.",
        price: 3299,
        newPrice: 2999,
        onSale: true,
        images: ["/collectiondemo.jpg", "/collectiondemo.jpg"],
        colors: ["Beige", "Camel", "Brown", "Grey", "Ivory"],
      },
    ],
  },
];


