import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/MainComp/Header";
import {Montserrat} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
