import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/MainComp/Header";
import { montserrat } from "@/lib/fonts";
import Footer from "@/components/MainComp/Footer";
import { CartContextProvider } from "@/context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.className}`}
      >
        <CartContextProvider>
          <Header />
          {children}
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
